#!/bin/bash

source installer-ansible-pull-role
SERVICE_ENV='service=clustercontrol-nginx service_webserver=nginx'

pullrole stable ${SERVICE_ENV}

echo "Adding description to CWM" | log
descriptionAppend "CC Admin Web UI: https://${CWM_DISPLAYED_ADDRESS}"
descriptionAppend "CC Email: ${ADMINEMAIL}"
descriptionAppend "CC Username: root"
descriptionAppend "CC Password: ${ADMINPASSWORD}" 
descriptionAppend " "
