#!/bin/bash

source installer-ansible-pull-role
SERVICE_ENV='service=clustercontrol-nginx service_webserver=nginx'

pullrole stable ${SERVICE_ENV}

echo "Adding description to CWM" | log
descriptionAppend "CC Admin Web UI: https://${CWM_DOMAIN}"
descriptionAppend "CC Email: ${ADMINEMAIL}"
descriptionAppend "CC Username: root"
descriptionAppend "CC Password: ${ADMINPASSWORD}" 
descriptionAppend " "

DescContent=$(cat ~/description.txt)
updateServerDescription "$DescContent"

rm -rf /opt/installer-ansible
rm -rf ~/.ansible*