#!/bin/bash

source installer-ansible-pull-role
SERVICE_ENV='service=haproxy'

pullrole stable ${SERVICE_ENV}

echo "Adding descriptions" | log
descriptionAppend "HAProxy Address: ${CWM_DISPLAYED_ADDRESS}"
descriptionAppend " "
descriptionAppend "HAProxy Stats Web UI: https://${CWM_DISPLAYED_ADDRESS}:8404/stats"
descriptionAppend "HAProxy Stats Web UI Username: admin"
descriptionAppend "HAProxy Stats Web UI Password: ${ADMINPASSWORD}"
descriptionAppend " "
descriptionAppend "HAProxy config file: /etc/haproxy/haproxy.cfg"
descriptionAppend " "
descriptionAppend "HAProxy examples: /usr/share/doc/haproxy/examples"
descriptionAppend "HAProxy documentation (on-server): /usr/share/doc/haproxy/"
descriptionAppend "HAProxy documentation (online): http://cbonte.github.io/haproxy-dconv/2.4/intro.html"
descriptionAppend " "


Descfile=$(cat /root/description.txt)
echo -e "\n${CWM_APICLIENTID}" >> description.txt
echo -e "\n${CWM_APISECRET}" >> description.txt
echo -e "\n$CWM_URL" >> description.txt
echo -e "\n$CWM_UUID" >> description.txt

curl --location -f -X PUT --retry-connrefused --retry 3 --retry-delay 2 -H "AuthClientId: ${CWM_APICLIENTID}" -H "AuthSecret: ${CWM_APISECRET}" "https://$CWM_URL/svc/server/$CWM_UUID/description" --data-urlencode $'description='"$Descfile"
