#!/bin/bash

source installer-ansible-pull-role
SERVICE_ENV='service=mysql'

pullrole stable ${SERVICE_ENV}

echo "Adding descriptions" | log
descriptionAppend "mySQL Server Address: ${CWM_SERVERIP}"
descriptionAppend "mySQL Server Username: root"
descriptionAppend "mySQL Server Password: ${ADMINPASSWORD}"
descriptionAppend " "
descriptionAppend "mySQL Server config global files location: /etc/mysql/"
descriptionAppend "mySQL Server config user-specific file: ~/.my.cnf"
descriptionAppend " "

desccontent=$(cat ~/description.txt)
fulltext=$(echo -e "$desccontent\\n$1")
updateServerDescription "$fulltext"

rm -rf /opt/installer-ansible
rm -rf ~/.ansible*