#!/bin/bash

source installer-ansible-pull-role
source startup-cwm.sh
SERVICE_ENV='service=haproxy-broker'

pullrole stable ${SERVICE_ENV}

echo "Adding descriptions" | log
cat << EOF > /root/description.txt
HAProxy Address: ${CWM_DISPLAYED_ADDRESS}
HAProxy Stats Web UI: https://${CWM_DISPLAYED_ADDRESS}:8404/stats
HAProxy Stats Web UI Username: admin
HAProxy Stats Web UI Password: ${ADMINPASSWORD}
HAProxy config file: /etc/haproxy/haproxy.cfg
HAProxy examples: /usr/share/doc/haproxy/examples
HAProxy documentation (on-server): /usr/share/doc/haproxy/
HAProxy documentation (online): http://cbonte.github.io/haproxy-dconv/2.5/intro.html
EOF

export APICLIENTID=$(cat /root/guest.conf |grep apiClientId |cut -d '=' -f 2)
export APISECRET=$(cat /root/guest.conf |grep apiSecret |cut -d '=' -f 2)
export URL=$(cat /root/guest.conf |grep url |cut -d '=' -f 2)
export UUID=$(cat /root/guest.conf |grep serverid |cut -d '=' -f 2)

touch /root/description.sh
cat << EOF > /root/description.sh
#!/bin/bash

curl --location -f -X PUT --retry-connrefused --retry 3 --retry-delay 2 -H "AuthClientId: $APICLIENTID" -H "AuthSecret: $APISECRET" "https://$URL/svc/server/$UUID/description" --data-urlencode description@/root/description.txt
EOF
chmod +x /root/description.sh
cd /root/
at -f /root/description.sh now + 3 minutes

rm -rf /opt/installer-ansible
rm -rf ~/.ansible*
