#!/bin/bash

source installer-ansible-pull-role
SERVICE_ENV='service=redis'

pullrole stable ${SERVICE_ENV}

echo "Adding descriptions" | log
descriptionAppend "Redis IP Address: ${CWM_DISPLAYED_ADDRESS}"
descriptionAppend " "

desccontent=$(cat ~/description.txt)
fulltext=$(echo -e "$desccontent\\n$1")
updateServerDescription "$fulltext"

rm -rf /opt/installer-ansible
rm -rf ~/.ansible*
