#!/bin/bash

source installer-ansible-pull-role
source startup-cwm.sh
SERVICE_ENV='service=haproxy-broker'

pullrole stable ${SERVICE_ENV}

echo "Adding descriptions" | log
echo "HAProxy Address: ${CWM_DISPLAYED_ADDRESS}" >> /root/description.txt
echo " " >> /root/description.txt
echo "HAProxy Stats Web UI: https://${CWM_DISPLAYED_ADDRESS}:8404/stats" >> /root/description.txt
echo "HAProxy Stats Web UI Username: admin" >> /root/description.txt
echo "HAProxy Stats Web UI Password: ${ADMINPASSWORD}" >> /root/description.txt
echo " " >> /root/description.txt
echo "HAProxy config file: /etc/haproxy/haproxy.cfg" >> /root/description.txt
echo " " >> /root/description.txt
echo "HAProxy examples: /usr/share/doc/haproxy/examples" >> /root/description.txt
echo "HAProxy documentation (on-server): /usr/share/doc/haproxy/" >> /root/description.txt
echo "HAProxy documentation (online): http://cbonte.github.io/haproxy-dconv/2.5/intro.html" >> /root/description.txt
echo " " >> /root/description.txt

APICLIENTID=$(apiClientId)
APISECRET=$(apiSecret)
URL=$(cat guest.conf |grep url |cut -f 2 -d"=")
UUID=$(cat guest.conf |grep serverid |cut -f 2 -d"=")

curl --location -f -X PUT --retry-connrefused --retry 3 --retry-delay 2 -H "AuthClientId: ${APICLIENTID}" -H "AuthSecret: ${APISECRET}" "https://$URL/svc/server/$UUID/description" --data-urlencode description@/root/description.txt

rm -rf /opt/installer-ansible
rm -rf ~/.ansible*
