#!/bin/bash

source installer-ansible-pull-role
SERVICE_ENV='service=redis'

pullrole stable ${SERVICE_ENV}

echo "Adding descriptions" | log
descriptionAppend "Redis IP Address: ${CWM_DISPLAYED_ADDRESS}"
descriptionAppend " "

DescContent=$(cat ~/description.txt)
updateServerDescription "$DescContent"

rm -rf /opt/installer-ansible
rm -rf ~/.ansible*
