#!/bin/bash

source installer-ansible-pull-role
SERVICE_ENV='service=redis'

pullrole stable ${SERVICE_ENV}

echo "Adding descriptions" | log
descriptionAppend "Redis IP Address: ${CWM_DISPLAYED_ADDRESS}"
descriptionAppend " "