#!/bin/bash

source installer-ansible-pull-role
SERVICE_ENV='service=drupal'

pullrole stable ${SERVICE_ENV}

echo "Adding descriptions" | log
descriptionAppend "Drupal Web UI: https://${CWM_DISPLAYED_ADDRESS}/user/login"
descriptionAppend "Drupal Username: admin"
descriptionAppend "Drupal Password: ${ADMINPASSWORD}"
descriptionAppend " "

DescContent=$(cat ~/description.txt)
updateServerDescription "$DescContent"

rm -rf /opt/installer-ansible
rm -rf ~/.ansible*